### PR TITLE
Update ml-agents to v0.13.1

### PR DESCRIPTION
**Pull request by MarcoMeter**
I consecutively updated ml-agents version by version from v0.10.0 to v0.13.1.
Unity version is still 2019.2.*.
Version 2019.3.* might comes with performance drops, which will need further investigation.

I accidentally did not include these fixes, so I added them manually on my Update branch:
- Fix bug in exit door future theme texture (fe4be86)
- Fix for push block trigger spawning (51dac2e)

This is probably why this pull request cannot be merged automatically.

And be aware of #16

### CODE REVIEW

**Comment by MarcoMeter** [comment]
@awjuliani 
No feedback yet?

**Comment by awjuliani** [comment]
Hi @MarcoMeter 

Apologizes. I haven't been able to take a look at this yet. I have it on my to-do list, and plan to take a look in the next few days.

**Comment by MarcoMeter** [comment]
Since ml-agents v0.14.0 was just released, I consider updating this PR maybe next week.

**Comment by awjuliani** [comment]
Hi @MarcoMeter,

We've discussed this a little internally. We are planning on having our first preview package release of ML-Agents in the next few weeks. I think that will be the point that we'd like to port Obstacle Tower to the latest release, as it will allow us to clean up the codebase at that point. Thanks for the effort you've put in here though in the mean-time.

**Comment by MarcoMeter** [comment]
Hi @awjuliani,
is there anything that I could contribute at the moment?
I'd love to see OT running much faster.

**Comment by awjuliani** [comment]
We are working on a PR that will upgrade the project to 1.0 release of ML-Agents. Thanks again @MarcoMeter for this effort on the earlier upgrade. Sorry we weren't able to use it. 

1.0 PR: https://github.com/Unity-Technologies/obstacle-tower-source/pull/19

**Pull request closed without merging**
